### PR TITLE
Bootstrap styling added

### PR DESCRIPTION
**Pull request by mariosemes**
Added Bootstrap styling.
Should work locally, no CDN was inserted.

Please test it out before MERGING to main.

### CODE REVIEW

**Comment by natpuch** [comment]
Thank you for the pull request!

First, could you please change to dev branch as you mentionned on reddit please?

Then, in the `docker-compose.yml` file, a volume is needed for the `assets`:
```
volumes:
        - ./assets/:/var/www/html/assets/
        - ./index.htsh:/var/www/html/index.htsh
        - ./pdf/:/tmp/pdf/
```

Could you get this to work? I have an error when running `build.sh`:
`ERROR : Unmatched ?&gt; in file index.htsh (Line 54)`

I could not find where was the missing `<`.

**Comment by mariosemes** [comment]
I am not able to contribute this moment. Can you try to push the fixes to dev?

**Comment by natpuch** [comment]
The problem with the unmatched `<` was the indentation. Apparently, for [bash_on_steroids](https://github.com/tinoschroeter/bash_on_steroids) bash parts needs to be aligned left.

I corrected that and made the changes. Everything works now.
It is much better with styling!

Is it possible to make the page reload in the same tab when combining, compressing or splitting?

**Comment by mariosemes** [comment]
Not impossible tbh. More like ajax and js then clean html

**Comment by natpuch** [comment]
I cannot get this to work for now. I'll re-take a look at it later.

**Comment by natpuch** [comment]
Done! Everything is in dev. Closing this pull-request.

Thank you for the help! It is much better with Bootstrap styling.

**Pull request closed without merging**
